### ISSUE TITLE
Question: Firmware URL

### ISSUE THREAD

**Issue by AlleSchonWeg** [TA2k/ioBroker.gruenbeck#11]
Hi,
sorry to ask you, but i can't found any infos about the firmware URL's and versions from the sd devices.  Do you have any URL's from Sd Fimware and version infos?
Thank you

**Comment by TA2k** [comment]
Die Firmware sollte im Adapter unter softwareVersion mit ausgegeben werden

**Comment by AlleSchonWeg** [comment]
Ja, das habe ich gesehen. Mich interessiert allerdings, ob es eine Versionshistorie gibt und welche gerade die aktuelle ist.
Grüße

**Comment by TA2k** [comment]
Sowas ist mir nicht bekannt.
