### ISSUE TITLE
Adapter liefert keine Daten mehr

### ISSUE THREAD

**Issue by tomschlde** [TA2k/ioBroker.gruenbeck#14]
Hallo zusammen,
der Adapter liefert seit dem 25.7 keine Daten mehr.
Es werden nur noch Daten geliefert, wenn gleichzeitig die Grünbeck-App zugreift.

![Grünbeck](https://user-images.githubusercontent.com/59179041/89025711-a4c85880-d327-11ea-8c03-76ad91b10f02.PNG)

**Comment by rywr** [comment]
Hallo,

ich kann das Verhalten bestätigen. Anbei ein Auszug aus dem Log:

gruenbeck.0 | 2020-07-31 22:46:03.877 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | -- | --
gruenbeck.0 | 2020-07-31 22:46:03.877 | error | at endReadableNT (_stream_readable.js:1221:12)
gruenbeck.0 | 2020-07-31 22:46:03.877 | error | at IncomingMessage.emit (events.js:327:22)
gruenbeck.0 | 2020-07-31 22:46:03.877 | error | at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:236:11)
gruenbeck.0 | 2020-07-31 22:46:03.877 | error | at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
gruenbeck.0 | 2020-07-31 22:46:03.877 | error | at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
gruenbeck.0 | 2020-07-31 22:46:03.877 | error | (1292) Error: Request failed with status code 500
gruenbeck.0 | 2020-07-31 22:46:03.873 | error | (1292) unhandled promise rejection: Request failed with status code 500
Unhandled | 2020-07-31 22:46:03.869 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

bzw.:

gruenbeck.0 | 2020-07-31 22:29:04.770 | error | (1277) Error: Request failed with status code 400
-- | -- | -- | --
gruenbeck.0 | 2020-07-31 22:29:04.770 | error | (1277) Refreshtoken error


Ein Neustart des Adapters bringt keinen Erfolg. 
Öffnet man paralle die Grünbeck-App auf dem Telefon und ruft die aktuellen Daten ab, dann erhält der ioBroker-Adapter ebenfalls aktuelle Werte. Der nächste Abruf von ioBroker funktioniert dann wieder nicht mehr.

Hat Grünbeck oder Azure die Authentifizierung geändert?

**Comment by rc-itcon** [comment]
Hallo,

ich kann dieses Verhalten bestätigen, jedoch konnte ich folgendes Herausfinden:

Beim ersten mal Laden, muss die App am Handy offen sein. Danach kann die APP geschlossen werden und der Adapter sogar neugestartet werden. Funktionen bleiben erhalten.

App kann danach auch im Hintergrund geschlossen werden.

**Comment by rywr** [comment]
@TA2k: Ist eine Korrektur für die Grünbeck-Daten geplant? Oder ist der Support für den Adapter eingestellt? 
Eine kurze Rückmnelodung des Entwicklers wäre schön, ob hier in Zukunft Unterstützung bzw. Anpassungen an Azure/Grünbeck zu erwarten sind. Danke dafür :-)

Die Situation ist immer noich die gleiche. Aktuelle Daten erhält der Adapter nur, wenn parallel zur Anfrage die Grünbeck-App eine Abfrage der Live-Daten macht.
Die "normalen" Daten wie letzter Wasser-/Salzverbrauch (die über REST und nicht über Websocket abgefragt werden) funktionieren.
Es liegt lediglich an der Anmeldung zur Websocket-Anfrage (Nodered?).

**Comment by rywr** [comment]
Hallo,
ich habe zu dem Problem nach dem SignalR-Code type:6 folgendes gefunden:

https://docs.beaxy.com/docs/connection

type:6 ist eine keep-alive-Nachricht, die mit dieser Nachricht beantwortet werden muss (soweit ich das verstanden habe),
{
  "type": 2,
  "invocationid": 0,
  "item": {
    ...
  }  
}

Vielleicht hilft das bei der Suche nach einer Lösung.

**Comment by TA2k** [comment]
fixed
