### ISSUE TITLE
No Data provided at all

### ISSUE THREAD

**Issue by tomschlde** [TA2k/ioBroker.gruenbeck#16]
Hi all,
nice that you continue getting this adapter to work.
I used it until the adapter stopped working with my SD18 -> see issue #14.
So i reinstalled the adapter, signed in and no data is provided to the objects.
All objects are populated, but all with the "false" as content.
The data is starting to fire if the app is started in paralell. (same behvior as before...) also with no useable data...
Debug log has no useful infos...
Can you help?

TIA Thomas

`gruenbeck.0 | 2020-12-17 21:07:38.736 | debug | (13427) {"type":6}
-- | -- | -- | --
gruenbeck.0 | 2020-12-17 21:07:32.736 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:07:32.058 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:31.172 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:30.076 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:29.234 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:28.000 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:27.735 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:07:27.159 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:26.049 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:24.955 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:23.853 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:23.059 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:22.737 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:07:22.215 | debug | (13427) {"type":1,"target":"SendMessageToDevice","arguments":[{"id":"BS40014838","type":"Current","ibuiltindev":true,"isncu":"202006251459","mregpercent1":100,"mregpercent2":0,"mremregstep":0,"mregsta
gruenbeck.0 | 2020-12-17 21:07:21.531 | debug | (13427) {"type":1,"target":"SendOneTimeMessageToDevice","arguments":[{"id":"BS40014838","type":"CurrSlow","ibuiltindev":true,"isncu":"202006251459","mcountreg":89,"mcountwater1":50087,"mcountwater2":0
Here the app was opened........
gruenbeck.0 | 2020-12-17 21:07:17.735 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:07:11.738 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:07:05.737 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:06:59.736 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:06:54.733 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:06:48.733 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:06:43.732 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:06:37.732 | debug | (13427) {"type":6}
gruenbeck.0 | 2020-12-17 21:06:37.281 | debug | (13427) {"type":1,"target":"SendOneTimeMessageToDevice","arguments":[{"id":"BS40014838","type":"CurrSlow","ibuiltindev":true,"isncu":"202006251459","mcountreg":89,"mcountwater1":50087,"mcountwater2":0
gruenbeck.0 | 2020-12-17 21:06:37.192 | debug | (13427) {}
gruenbeck.0 | 2020-12-17 21:06:37.157 | debug | (13427) WS connected
`

**Comment by TA2k** [comment]
Fixed

**Comment by kep42010** [comment]
Hi, bei mir kommen leider auch keine Daten an? Habe gelesen, dass das Problem gestern behoben wurde aber leider hat sich bei mir nichts getan.

**Comment by TA2k** [comment]
Auch mit der 0.0.24? Welcher Fehler kommt

**Comment by kep42010** [comment]
Leider ja. Der Adapter ist grün aber es kommen keine Daten an. Ich frag mich auch ob mit den Zugangsdaten was nicht stimmt, wundert mich dann eben nur das er grün ist...
Kenne mich leider noch nicht so gut aus mit dem iobroker, daher habe ich dir mal ein paar screenshots angehängt. Habe versucht den Adapter 2 mal neu zu starten --> Siehe Log
Wh liegt der Fehler iwo an meinen Einstellung aber ich weiß einfach nicht woran. Vll fällt dir ja was ins Auge.

Besten Dank im Voraus und Grüße

<img width="1085" alt="Adapter" src="https://user-images.githubusercontent.com/76907717/103506451-08b5f680-4e5d-11eb-96db-cb041026c9ef.png">
<img width="1060" alt="Objekte" src="https://user-images.githubusercontent.com/76907717/103506469-11a6c800-4e5d-11eb-9e72-638a26b881d6.png">
<img width="1096" alt="Log" src="https://user-images.githubusercontent.com/76907717/103506472-14092200-4e5d-11eb-82e2-ec3986bb6a44.png">

**Comment by TA2k** [comment]
Caclulated ist nur für SC anlagen relevant
SD sollte als eignes Gerät auftauchen

**Comment by kep42010** [comment]
Ok, sorry das mit calculated war mir nicht klar. Die anderen Punkte wie Info, etc sind auch auf false.
Unter SoftliQ bekomme ich Daten Geräte ID, täglicher Wasserverbrauch. Damit muss ich dann mal etwas spielen.
