### ISSUE TITLE
History data for water and salt usage

### ISSUE THREAD

**Issue by sarnau** [TA2k/ioBroker.gruenbeck#21]
Not sure if this is interesting, but in the same way the device info can be read via `/api/devices/DEVICEID/?api-version=…` can you read the history of measurements via `/api/devices/DEVICEID/measurements/water/?api-version=…` and  `/api/devices/DEVICEID/measurements/salt/?api-version=…` which will return a JSON block as well.

**Comment by TA2k** [comment]
added in 0.0.26
