### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by jk-andersen** [TA2k/ioBroker.gruenbeck#23]
Have an issue after a fresh first install loging in - Looks like an URL-Issue? witch devices//realtime?

gruenbeck.0 | 2021-01-07 11:58:14.210 | info | (1450) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
gruenbeck.0 | 2021-01-07 11:58:14.209 | info | (1450) terminating
gruenbeck.0 | 2021-01-07 11:58:14.206 | error | (1450) unhandled promise rejection: undefined
gruenbeck.0 | 2021-01-07 11:58:11.377 | info | (1450) starting. Version 0.0.26 in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v14.15.4, js-controller: 3.1.6
gruenbeck.0 | 2021-01-07 11:58:07.290 | error | (1429) Error: Request failed with status code 401
gruenbeck.0 | 2021-01-07 11:58:07.290 | error | (1429) https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices//realtime/leave?api-version=2020-08-03
gruenbeck.0 | 2021-01-07 11:58:07.068 | info | (1429) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
gruenbeck.0 | 2021-01-07 11:58:07.068 | info | (1429) terminating
gruenbeck.0 | 2021-01-07 11:58:07.067 | info | (1429) Got terminate signal TERMINATE_YOURSELF
gruenbeck.0 | 2021-01-07 11:57:30.386 | warn | (1429) [START] No IP-address set
gruenbeck.0 | 2021-01-07 11:57:30.378 | info | (1429) starting. Version 0.0.26 in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v14.15.4, js-controller: 3.1.6

**Comment by TA2k** [comment]
fixed with 0.0.27
