### ISSUE TITLE
all calculated data points stay false

### ISSUE THREAD

**Issue by Chris-We** [TA2k/ioBroker.gruenbeck#24]
all data points under "calculated" stay false

I have a SD18 which values are updated

**Expected behavior*
values should be calculated and updated

**Screenshots & Logfiles**  
<img width="993" alt="image" src="https://user-images.githubusercontent.com/59453969/104233550-5c72a200-5452-11eb-8fba-8c9cc0895a4c.png">

**Versions:**  
 - Adapter version: 0.0.21
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: docker

**Additional context**

**Comment by TA2k** [comment]
They belong to SC devices
