### ISSUE TITLE
Wie setzt man den Schleichwasser Alarm zurück?

### ISSUE THREAD

**Issue by ZeroQool007** [TA2k/ioBroker.gruenbeck#25]
Hallo, 

bei mir steht das Schleichwasser erkannt worden ist, aber kann das so nicht bestätigen, da die Aussenwasserhähne komplett abgedreht sind und im Haus sehe ich kein Leck :-) . Wie setze ich die Meldung zurück?

Danke

**Comment by m4ding** [comment]
Habe ich mal in einem Forum gefunden. Über die Webseite mit dem Code anmelden

![CD596EF9-D04A-4D25-BCB8-D34CA02AC8BD](https://user-images.githubusercontent.com/65028008/158008593-daf021f4-1d77-4cb4-8583-bc21a4faceff.jpeg)
