### ISSUE TITLE
Fehler im Log und keine Daten mehr seit 0.0.28 

### ISSUE THREAD

**Issue by tomschlde** [TA2k/ioBroker.gruenbeck#27]
Die Datenübertragung meiner SD stoppt mit den Einträgen im Log nach dem Update auf due aktuelle Version.

gruenbeck.0 | 2021-01-31 15:08:59.933 | error | (10653) Error: Request failed with status code 429
-- | -- | -- | --
gruenbeck.0 | 2021-01-31 15:08:53.420 | error | (10653) No Data since 2min start login
gruenbeck.0 | 2021-01-31 15:02:57.585 | error | (10653) Error: Request failed with status code 429
gruenbeck.0 | 2021-01-31 15:02:55.773 | error | (10653) No Data since 2min start login

der Fehler kommt auch direkt nach dem Start der Instanz:
gruenbeck.0 | 2021-01-31 15:17:38.880 | error | (11032) Error: Request failed with status code 429
-- | -- | -- | --

0.0.27  lief vorher einwandfrei.

**Comment by rywr** [comment]
Das Problem tritt auch mit Version 0.0.24 auf (seit heute). Anbei das Log:

gruenbeck.0 | 2021-01-31 14:00:41.946 | error | (12266) Error: Request failed with status code 500
-- | -- | -- | --
gruenbeck.0 | 2021-01-31 14:00:41.944 | error | (12266)  https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BSxxxxxxxxx/realtime/refresh?api-version=2020-04-07
gruenbeck.0 | 2021-01-31 14:00:11.638 | error | (12266) Error: Request failed with status code 429
gruenbeck.0 | 2021-01-31 14:00:08.453 | info | (12266) starting. Version 0.0.24 in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v12.19.0, js-controller: 3.1.5
 
Vielleicht ist das auch nur ein temporäres Problem des Servers...

**Comment by rywr** [comment]
Der Abruf funktiiniert wieder. Vermutlich doch nur ein Serverproblem.

**Comment by tomschlde** [comment]
429 heißt wohl "too many requests" - komisch ist nur, dass es direkt nach dem Update kam :(

**Comment by rywr** [comment]
In der Grünbeck-App bekommt man auch keine Verbrauchsdaten. Statistik geht, Regenerierung anfordern geht auch. Es scheint daher ein Serverproblem bei den Websocket-Daten zu sein.

**Comment by TA2k** [comment]
Ich würde mal den Adapter für 24h deaktivieren ob es dann wieder geht

**Comment by TA2k** [comment]
Wie ist die Verbindung zur Zeit?

**Comment by rywr** [comment]
Sieht recht gut aus. Die Daten werden abgerufen.
Ab und zu gibt es mal Serverfehler, aber nur sporadisch, z.B.
7:40 http 500
4:30 http 500
2:00 http 429 (könnte evtl. am Adapter-Restart alle 2h liegen)
0:00 http 429

Der 429-Fehler könnte vielleicht durch zu schnelle Abrufwiederholung bei Adapter-Restart kommen. Tritt aber nicht immer auf.
Ich werde weiter beobachten. Solange das Einzelfälle sind, ist alles ok.

**Comment by tomschlde** [comment]
Ist wieder OK, war wohl eher ein Serverproblem.
