### ISSUE TITLE
Adapter don't refresh Values

### ISSUE THREAD

**Issue by joisphe** [TA2k/ioBroker.gruenbeck#3]
Hi,

first thank you for develop this great adapter.
I used it also with SC18 and it works great.

I'm using 0.0.13

With SD 23 my IO Broker only refresh values if i open the Grünbeck App on my Smartphone.
If it is open and i push the "refresh button" in the app the values will actualize.

My workaround is a virtual machine with bluestacks and Grünbeck app.
The button is pushed by a mouse macro every 30 seconds, so is works.

The problem is, every time if power supply fails, i have to start bluestacks and start the app and config makro recorder.

Thanks in advance

**Comment by TA2k** [comment]
The support ist not tested very good I will have a look and post an update in the forum

**Comment by joisphe** [comment]
Let me know if i can support you.

**Comment by TA2k** [comment]
Fixed with new version
