### ISSUE TITLE
A lot of log entrys after update to js controller 3.3

### ISSUE THREAD

**Issue by luigibt** [TA2k/ioBroker.gruenbeck#33]
After iobroker update to js controller version 3.3. there are a lot of log entrys every minute.
Example below.

gruenbeck.0 | 2021-05-26 15:30:41.931 | info | State value to set for "gruenbeck.0.error.D_K_10_16" has to be type "string" but received type "number"
-- | -- | -- | --
gruenbeck.0 | 2021-05-26 15:30:41.878 | info | State value to set for "gruenbeck.0.error.D_K_10_15" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.869 | info | State value to set for "gruenbeck.0.error.D_K_10_14" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.864 | info | State value to set for "gruenbeck.0.error.D_K_10_13" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.857 | info | State value to set for "gruenbeck.0.error.D_K_10_12" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.851 | info | State value to set for "gruenbeck.0.error.D_K_10_11" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.844 | info | State value to set for "gruenbeck.0.error.D_K_10_10" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.838 | info | State value to set for "gruenbeck.0.error.D_K_10_9" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.792 | info | State value to set for "gruenbeck.0.error.D_K_10_8" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.787 | info | State value to set for "gruenbeck.0.error.D_K_10_7" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.783 | info | State value to set for "gruenbeck.0.error.D_K_10_6" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.779 | info | State value to set for "gruenbeck.0.error.D_K_10_5" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.775 | info | State value to set for "gruenbeck.0.error.D_K_10_4" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.770 | info | State value to set for "gruenbeck.0.error.D_K_10_3" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.766 | info | State value to set for "gruenbeck.0.error.D_K_10_2" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:41.762 | info | State value to set for "gruenbeck.0.error.D_K_10_1" has to be type "string" but received type "number"
gruenbeck.0 | 2021-05-26 15:30:27.950 | info | State value to set for "gruenbeck.0.parameter.D_C_8_2" has to be type "number" but received type "string"
gruenbeck.0 | 2021-05-26 15:30:27.946 | info | State value to set for "gruenbeck.0.parameter.D_C_8_1" has to be type "number" but received type "string"
gruenbeck.0 | 2021-05-26 15:30:27.866 | info | State value to set for "gruenbeck.0.info.D_A_3_1" has to be type "string" but received type "number"

**Versions:**  
 - Adapter version: 0.0.29
 - JS-Controller version: 3.3.11
 - Node version: 12.22.1
 - Operating system: Linux Raspberry PI

**Comment by loebse** [comment]
Has there been any update on this? I am facing the same issue. I guess the data type for the errors is wrong. It should be "string" and not "number".

I changed it for myself in "io-package.json" which seems to solve the issue.

Cheers,
Sebastian

**Comment by TA2k** [comment]
can you please share your json

**Comment by loebse** [comment]
Please find attached:
[io-package.json.zip](https://github.com/TA2k/ioBroker.gruenbeck/files/7838796/io-package.json.zip)

**Comment by TA2k** [comment]
is mit 0.0.32 gefixt

**Comment by loebse** [comment]
Thanks for updating it @TA2k

However, I think it is a bit more complex than anticipated. 

The error states that receive a value are receiving a string (e.g. "E7_h14734") so the fix is working here. But the error states that do not have a value receive a "0" as number. So what is happening now is the following:

`State value to set for "gruenbeck.0.error.D_K_10_10" has to be type "string" but received type "number"`

I guess you would need to convert the "0" as a number into a "0" as a string or leave it empty and only fill it if there is really an error value.

![image](https://user-images.githubusercontent.com/39953358/148903281-7b9d6754-396e-43c7-b426-f19e235e9674.png)

**Comment by TA2k** [comment]
please reinstall again
