### ISSUE TITLE
Technische Fragen zu Parameter-Änderung und Start der Regeneration

### ISSUE THREAD

**Issue by RonnyWinkler** [TA2k/ioBroker.gruenbeck#35]
Hallo TA2k,

dies ist kein Bug-Report sondern eine technische Frage. Ich hoffe, du kannst mir weiterhelfen.
Ich habe auf Basis deines ioBroker-Adapter eine App für das Smarthome-System Homey erstellt. Vielen Dank für die technische Basis und die API-Aufrufe. Das hat für die Adaption wirklich weitergeholfen.
Zur Info:
https://homey.app/de-de/app/de.ronnywinkler.homey.gruenbeck/Gr%C3%BCnbeck/

Ich habe in deinem Code die Funktion pushMgParameter( ) gesehen. Lassen sich damit alle Parameter eines SD-Geräts setzen, die im ioBroker-Adapter unter softliQ/D.../parameters aufgelistet sind? Hast du eine technische Beschreibung für gültige Inhalte, die verwendbar sind?
Außerdem habe ich mich gefragt, ob man auch die Regeneration manuell wie in der Grünbeck-App starten kann. Kennst du dafür auch die API-URL und die Parameter?
Ich wäre dir für weiterführende Info dankbar. 

Viele Grüße
Ronny

**Comment by TA2k** [comment]
Ich habe keine SD anlage aber laut code werden sich alle parameters geholt die dann auch gesetzt werden können

**Comment by RonnyWinkler** [comment]
Danke für die Rückmeldung. Dann kann ich mal mit dem Modus experimentieren.
Ob bzw. wie eine Regenerierung gestartet wird, weißt du aber nicht zufällig?

**Comment by RonnyWinkler** [comment]
Hallo TA2k,
die Optionen der softliQ-SD setzen klappt wunderbar. 
Ich stehe noch vor der Herausforderung, die Regenerierung zu starten und bräuchte dazu Infos zur API...

Woher hast du eigentlich die Infos zur API? Hast du Dokumentationen von Grünbeck selbst?
Oder kann man die API-Definition aufrufen? Ich habe allerdings noch keine Möglichkeit gefunden, eine Swagger-Definition o.ä. zu bekommen (über https://prod-eu-gruenbeck-api.azurewebsites.net/...). Wenn du dazu Infos hast, wäre ich dir dankbar. Gern auch "offline" direkt per Mail o.ä. 
Vielen Dank vorab.

**Comment by RonnyWinkler** [comment]
Hat sich erledigt... Hab's mit PCAP gefunden...
POST /api/devices/softliQ.D/BSXXXXXXXX/regenerate?api-version=2021-07-05 
Body: {}

**Comment by seh-len** [comment]
@TA2k kannst du die manuelle Regeneration für die SD-Anlagen bitte auch über den Adapter zur Verfügung stellen?
