### ISSUE TITLE
Error with Salt and Water Measurements

### ISSUE THREAD

**Issue by jk-andersen** [TA2k/ioBroker.gruenbeck#38]
Hi there,

i got a new SD18 installed earlier this week. Everything works besides two daily errors:

<html>
<body>

gruenbeck.0 | 2021-11-19 16:53:20.712 | error | Failed to get salt
-- | -- | -- | --
gruenbeck.0 | 2021-11-19 16:53:20.711 | error | Error: The id "softliQ.D/BS40049931.measurements.salt." is invalid. Ids are not allowed to end in "."
gruenbeck.0 | 2021-11-19 16:53:20.672 | error | Failed to get water
gruenbeck.0 | 2021-11-19 16:53:20.671 | error | Error: The id "softliQ.D/BS40049931.measurements.water." is invalid. Ids are not allowed to end in "."

</body>
</html>

**Comment by TA2k** [comment]
fixed with 0.0.31
