### ISSUE TITLE
Objekte können nicht ausgelesen werden

### ISSUE THREAD

**Issue by mymofe** [TA2k/ioBroker.gruenbeck#46]
Ich habe versucht, die Daten des Grünbeck-Adapters mittels Node-Red an meine Loxone zu senden.
Leider können die Werte des Grünbeck-Adapters jedoch nicht ausgelesen werden, da die Objekt-ID ein etwas ungünstiges Zeichen "/" beinhaltet. Dadurch kann das Topic nicht richtig wiedergegeben werden. 

Siehe folgendem Screenshot:

![image](https://user-images.githubusercontent.com/104419823/165249312-9a8f5a53-ae72-4125-998d-c5ccbd9132fa.png)

Hier wird die Object-ID "D/BS40012..." erzeugt.

Ist es möglich die Object-ID zu ändern, damit dieses "/" zb. durch einen _ ersetzt wird?

**Comment by TA2k** [comment]
Habe ein Option in 0.0.40 eingebaut
