### ISSUE TITLE
Adapter cannot connect to device or service (SD21)

### ISSUE THREAD

**Issue by dome227** [TA2k/ioBroker.gruenbeck#48]
Hello together,

at first - thanks for providing this adapter to ioBroker. 
After connecting myGruenbeck account to your adapter, the instance showed me an error: 
- Connected to host
- Alive
- ERROR: Connected to device or service

I checked out the network connection to my SD21 and it works. 
The gruenbeck App works aswell. 

I've installed 0.0.34 and upgraded to 0.0.41. 
Both versions won't work with my system. 

Does anyone have an idea what could be the problem? 

Thanks a lot in advance! 

Best Regards,
Dominik

![gruenbeck_adapter](https://user-images.githubusercontent.com/83926632/175823156-2341dbdb-b31a-4626-a643-b04692b566ca.jpg)

**Comment by TA2k** [comment]
Log wäre wichtig

**Comment by dome227** [comment]
Hi TA2k, 

vielen Dank für die Rückmeldung. 
In den Logs gibt er mir nur folgenden Output: 

![gruenbeck_adapter_log](https://user-images.githubusercontent.com/83926632/175949486-7d092a89-486c-490e-88ea-eccd62dece3c.jpg)

Die Instanz bleibt nach wie vor gelb. 

Ich prüfe gleich nochmals ob meine SD21 eine aktuelle Firmware zur Verfügung hat. 

Viele Grüße,
Dominik

**Comment by TA2k** [comment]
Es fehlt der finale schritt. Nochmal login daten überprüfen und mal in der app ausloggen und einloggen

**Comment by dome227** [comment]
Hallo @TA2k ,

vielen Dank für deine schnelle Rückmeldung.
Ich habe den Adapter nochmal gelöscht, nochmal hinzugefügt und ein Firmware Update auf 02.46 durchgeführt (Grünberg Anlage). 

Nun ist die Anlage mit dem ioBroker verbunden, allerdings bekomme ich keine Werte rein. 

![gruenbeck_adapter_werte](https://user-images.githubusercontent.com/83926632/177157968-4de6a85a-9630-4a11-bd80-4a3110ee5e23.jpg)

Muss ich hier noch etwas an der Anlage entsprechend freigeben? Oder woran könnte das liegen? 
Möchte die Anbindung gerne nutzen, um die Grünbeck Werte via MQTT an meinen Home Assistant weiter zu geben - hier übernimmt er den Wert "(NULL)" als "Unbekannt". 

Viele Grüße und vielen Dank vorab! 
Dominik

**Comment by mlampe71** [comment]
Hi, 
konntet ihr schon was in Erfahrung bringen? Bin an der gleichen Stelle wie @dome227. Verbindung steht, aber die Werte kommen nicht mit rüber.

**Comment by TA2k** [comment]
Gibt es denn Fehler im log. Welche Werte sind unter Stream sichtbar

**Comment by mlampe71** [comment]
Hallo TA2k,
nein, da gab es keine Fehler. Das Problem hat sich aber erledigt: es lag vor dem Monitor. Der Adapter funktioniert und ich sehe auch die Werte.
Trotzdem vielen lieben Dank für deine Hilfe.
