### ISSUE TITLE
Gruenbeck „Stream“ API Endpoint throws HTTP 500 error 

### ISSUE THREAD

**Issue by mrbwburns** [TA2k/ioBroker.gruenbeck#59]
**Describe the bug**  
See title and iobroker log:
gruenbeck.0
2024-06-12 13:16:30.787	error	Failed enter SD
gruenbeck.0
2024-06-12 13:16:30.786	error	AxiosError: Request failed with status code 500

I still get other data from the API, but nothing from the Stream subfolder.

**To Reproduce**  
1. Start fresh Installation of Gruenbeck Adapter v0.42, configure for SD18 
2. Wait for livebeat and connection checks to pass
3. check logs for error

**Expected behavior**  
I expect to get the Stream data as well.

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 0.42
 - Node.js: v18.20.3
 - JS-Controller version: 5.0.19
 - Operating system: Linux, docker (official image - v9.1.2)

**Additional Info:**
I also ckecked the endpoint via browser and just got an empty response. One level up I get a json response with the correct data. Not sure where the actual problem is, though.
Functioning URL: https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BS4xxxxxxx/

**Comment by TA2k** [comment]
wait for 24h
