### ISSUE TITLE
Can not enter username and password in configuration

### ISSUE THREAD

**Issue by Shengaton** [TA2k/ioBroker.gruenbeck#6]
**Describe the bug**  
In order to connect to the cloud username and password is needed. But I can only enter a hostname in the config page of the adapter.

**To Reproduce**  
1. Go to 'Instanzen / gruenbeck / config' in the admin interface
2. See no fields for user and password

**Expected behavior**  
Both fields should be present there and can be filled as an alternative to 'host'.

**Versions:**  
 - Adapter version: 0.0.12
 - JS-Controller version: 1.5.14 
 - Node version: v10.16.3 
 - Operating system: Linux

**Comment by TA2k** [comment]
Install Adapter via github and upload the adapter
