### ISSUE TITLE
Grünbeck SD221: Cannot start Regeneration

### ISSUE THREAD

**Issue by philipgo** [TA2k/ioBroker.gruenbeck#71]
Hello @TA2k ,

I replaced my SC18 with an SD21. It seems like the SC18 supported starting the regeneration through your adapter (I never tried if it works..)

Would it be possible to provide this function for the SD21 as well. This way I could move regeneration to times when no water is used/no one is at home.

@RonnyWinkler described the API endpoint here: https://github.com/TA2k/ioBroker.gruenbeck/issues/35#issuecomment-933011062

Thank you for looking into this!

**Comment by TA2k** [comment]
What error you receive when you trigger the regeneration?

**Comment by philipgo** [comment]
It works :)

I am sorry for the confusion. I only saw the button in the section "Parameter für SC-Anlagen" and then the referenced issue, so I assumed it was not implemented.

Sorry, this can closed. (If anyone else is as blind as I was: gruenbeck.0.softliQ.D/XY12345.parameters.regenerate ).
