### ISSUE TITLE
Instance not starting anymore

### ISSUE THREAD

**Issue by mswiege** [TA2k/ioBroker.gruenbeck#8]
Since month my instance is not starting anymore.
The log shows errors about a "file not found" ("Datei nicht gefunden") and then an error "Cannot read property 'length' of null".
Is the adapter in general not working anymore or is there just something wrong in my setup?

Logs are attached:
[gruenbeck.log](https://github.com/TA2k/ioBroker.gruenbeck/files/4013192/gruenbeck.log)

**Comment by TA2k** [comment]
It looks like your device behaving strange. You tried to power off and on again and check the ip of the device?
